# Jekyll Resume Theme

# Site settings
title: Jekyll Resume
email: 1009037308@qq.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: ""
url: "https://hyolynjang.github.io/jekyll-resume/"
name: Hyolyn Jang
job: Scholar
location: Guangzhou, CN
languages: markdown
twitter_username: Hyolyn
github_username:  HyolynJang
codepen_username:  Hyolyn
email_address: some@email.com

# Build settings
markdown: kramdown
